In [2]:
import numpy as np
n1=np.array([5,2,3,1,4,4])
print(n1)
print(n1.ndim)
print(n1.shape)


[5 2 3 1 4 4]
1
(6,)


In [3]:
n2=np.array([[5,3,2,6,1],[8,2,9,5,1]])
print(n2)
print(n2[0,2])
print(n2.ndim)


[[5 3 2 6 1]
 [8 2 9 5 1]]
2
2


In [4]:
n3=np.zeros([3,2],dtype="int")
print(n3)


[[0 0]
 [0 0]
 [0 0]]


In [5]:
n4=np.ones([3,3,4],dtype="int")
print(n4)


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [6]:
n_emp=np.empty([2,3])
print(n_emp)


[[0.00000000e+000 1.92765140e+164 1.37740591e-311]
 [1.37740591e-311 3.95252517e-323 5.92878775e-323]]


In [7]:
print(np.arange(10))
print(range)


[0 1 2 3 4 5 6 7 8 9]
<class 'range'>


In [8]:
num_range=np.arange(5,10)
print(num_range)


[5 6 7 8 9]


In [9]:
num_range=np.arange(5,20,3)
print(num_range)


[ 5  8 11 14 17]


In [10]:
numbers=np.linspace(5,20,8)
print(numbers)


[ 5.          7.14285714  9.28571429 11.42857143 13.57142857 15.71428571
 17.85714286 20.        ]


In [11]:
number1=np.full([3,2],35)
print(number1)


[[35 35]
 [35 35]
 [35 35]]


In [12]:
n_emp.fill(10)
print(n_emp)


[[10. 10. 10.]
 [10. 10. 10.]]


In [13]:
print(n1[-2])
print(n2[1,:])
print(n2[:,2])
print(n2[1,2])
n4[1,1,2]=10
print(n4)

4
[8 2 9 5 1]
[2 9]
9
[[[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]

 [[ 1  1  1  1]
  [ 1  1 10  1]
  [ 1  1  1  1]]

 [[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]]


In [14]:
print(n4.ndim)
print(n4.shape)
print(n4.size)
print(n4.dtype)
print(n4.itemsize)
print(n4.nbytes)


3
(3, 3, 4)
36
int64
8
288


In [15]:
print(np.sort(n1))
print(n2)
n20=np.sort(n2,axis=0)
print(n20)
n20=np.sort(n2,axis=1)
print(n20)


[1 2 3 4 4 5]
[[5 3 2 6 1]
 [8 2 9 5 1]]
[[5 2 2 5 1]
 [8 3 9 6 1]]
[[1 2 3 5 6]
 [1 2 5 8 9]]


In [16]:
n1d=np.array([1,2,3,4,5,6,7,8,9,10])
print(n1d)
n2d=n1d.reshape(2,5)
print(n2d)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
n11=np.arange(13,19)
print(n11)
nconcat=np.concatenate((n1,n11))
print(nconcat)


[13 14 15 16 17 18]
[ 5  2  3  1  4  4 13 14 15 16 17 18]


In [18]:
n_convert=np.arange(8)
print(n_convert)
n_convert1=n_convert[:,np.newaxis]
print(n_convert1)
n_convert2=n_convert[np.newaxis,:]
print(n_convert2)
print(n_convert.shape)
print(n_convert1.shape)
print(n_convert2.shape)
n_convert11=np.expand_dims(n_convert,axis=1)
print(n_convert11)
print(n_convert11.shape)

[0 1 2 3 4 5 6 7]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0 1 2 3 4 5 6 7]]
(8,)
(8, 1)
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [19]:
n50=np.arange(2,10)
print(n50)
print(n50[n50>3])
print(n50[(n50>3)&(n50<8)])

print(n50[3:7])


[2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7]
[5 6 7 8]


In [20]:
nss1=np.array([[12,16],[14,18]])
nss2=np.array([[22,26],[24,28]])
nss3=np.hstack((nss1,nss2))
print(nss3)
nss1=np.array([[12,16],[14,18]])
nss2=np.array([[22,26],[24,28]])
nss3=np.vstack((nss1,nss2))
print(nss3)
arr_split=np.arange(20)
new_arr_split=np.array_split(arr_split,3)
print(arr_split)
print(new_arr_split)


[[12 16 22 26]
 [14 18 24 28]]
[[12 16]
 [14 18]
 [22 26]
 [24 28]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13]), array([14, 15, 16, 17, 18, 19])]


In [22]:
arr_split=np.arange(20)
new_arr_split=np.hsplit(arr_split,4)
print(arr_split)
print(new_arr_split)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


In [23]:
n2=np.array([[5,3,2,6,1],[8,2,9,5,1]])
new_arr_split=np.vsplit(n2,2)
print(n2)
print(new_arr_split)


[[5 3 2 6 1]
 [8 2 9 5 1]]
[array([[5, 3, 2, 6, 1]]), array([[8, 2, 9, 5, 1]])]


In [24]:
arr_copy=arr_split
arr_split[2]=25
print(arr_copy)
arr_copy=arr_split[1:5]
arr_split[2]=25
print(arr_copy)


[ 0  1 25  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1 25  3  4]


In [25]:
arr_copy=arr_split.copy()
arr_split[3]=43
print(arr_split)
print(arr_copy)

[ 0  1 25 43  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1 25  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
print(nss1+nss2)
print(nss1*nss2)
print(arr_split.sum())
print(arr_split.max())
print(arr_split.min())
print(arr_split*10)
print(np.cos(arr_split))

[[34 42]
 [38 46]]
[[264 416]
 [336 504]]
253
43
0
[  0  10 250 430  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]
[ 1.          0.54030231  0.99120281  0.5551133  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


In [29]:
np.random.rand(3,3,3)
np.random.randint(10,size=(2,2))


array([[0, 2],
       [5, 9]], dtype=int32)